### ISSUE TITLE
Tag 2.0.3?

### ISSUE THREAD

**Issue by danielbachhuber** [bradt/live-comment-preview#6]
Up for tagging a 2.0.3? It would be nice to have 91abfc44606ffc4fb11553de35a442d2f7cbe572 in the WordPress.org version.

Thanks in advance

**Comment by bradt** [comment]
This plugin is pretty neglected as I don't actually use it on any of my sites anymore. Want commit access to GitHub and the .org repo?

**Comment by danielbachhuber** [comment]
Sure, that'd be great.

**Comment by bradt** [comment]
Done and done.

**Comment by dgw** [comment]
@danielbachhuber Did anything come of this? I still have the 91abfc4 error in my server logs using the WP.org version.

**Comment by danielbachhuber** [comment]
> Did anything come of this? I still have the 91abfc4 error in my server logs using the WP.org version.

I guess not. I'll tag a release right now.

**Comment by danielbachhuber** [comment]
... done http://plugins.trac.wordpress.org/changeset/1275663

**Comment by dgw** [comment]
Awesome, upgraded. Thanks!
